argo-cd:
  global:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        effect: NoSchedule
